language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
branches:
  only:
    - master
    - /^(feature|bugfix)\/.*$/
before_install:
  - "[[ $(python -V 2>&1 | grep -Po '(?<=Python )(.+)') == 3.4* ]] && pip install setuptools --upgrade || echo 'continue'"
# command to install dependencies
install:
  - pip install -r requirements.test.txt . --upgrade
# command to run tests
before_script:
  - mkdir -p out/unit
  - mkdir -p out/uat
script:
  - nosetests tests.unit -v --with-xunit --xunit-file=out/unit/nosetests.xml -s --debug=ExcelRobot
  - robot -L DEBUG -d out/uat -v type:xls ./tests/acceptance
  - robot -L DEBUG -d out/uat -v type:xlsx ./tests/acceptance
